In [2]:
#imports
import tensorflow as tf
import pickle5
import numpy as np
import glob
from phynteny_utils import statistics

In this notebook make comparisons between the unknowns in y and their results across the ten folds

In [3]:
models = glob.glob('test_data/test_model/*')

In [4]:
models = [tf.keras.models.load_model(m) for m in models]

In [5]:
x = pickle5.load(open('test_data/x_mini.pkl', 'rb'))
x = list(x.values())
y = pickle5.load(open('test_data/y_mini.pkl', 'rb'))
y = list(y.values())

In [7]:
# output size will change to 0*120

# need another way of masking the row to predict - could I mask just with one values
# make a new branch to run these tests
# maybe introduce a masking column?

array([[ 0.00e+00,  0.00e+00,  0.00e+00, ...,  0.00e+00,  9.18e+02,
         0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00, ..., -8.00e+00,  7.50e+02,
         1.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00, ...,  1.98e+02,  1.32e+03,
         0.00e+00],
       ...,
       [ 1.00e+00,  0.00e+00,  0.00e+00, ...,  0.00e+00,  0.00e+00,
         0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00, ...,  0.00e+00,  0.00e+00,
         0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00, ...,  0.00e+00,  0.00e+00,
         0.00e+00]])

In [8]:
# remove the masking
for i in range(len(x))[0:10]:

    #overwrite the masked row
    x[i][:,:10] = y[i][:,:10]

    #get the unkown indexes
    unk_idx = [j for j in list(np.where(x[i][:, 0] == 1)[0]) if j < np.where(x[i][:, 14] == 0)[0][0]]

    for u in unk_idx:

        #mask this unknown
        x[i][u, 0:10] = np.zeros(10)

        #make the predictions for this unknown
        yhat = [m.predict(x[i].reshape(1,120,16), verbose = False) for m in models]

        # make the predictions for this unknown
        scores = [yhat[i][0][u] for i in  range(10)]

        print([np.argmax(s) for s in scores])
        print(np.round(np.array(scores).sum(axis=0), decimals=2))
        print('\n')

[4, 4, 6, 6, 6, 6, 7, 6, 6, 6]
[0.01 0.05 0.   0.01 2.36 0.22 6.32 0.57 0.32 0.13]


[4, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[3.94 3.09 0.   0.01 1.91 0.21 0.42 0.16 0.07 0.19]


[0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
[5.67 2.78 0.   0.09 0.34 0.07 0.19 0.07 0.04 0.75]


[0, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[5.38 2.24 0.   0.02 1.43 0.03 0.39 0.33 0.07 0.11]


[4, 0, 4, 0, 0, 0, 0, 9, 0, 0]
[5.56 0.66 0.   0.05 1.95 0.04 0.37 0.64 0.08 0.64]


[0, 0, 0, 0, 0, 1, 0, 0, 0, 1]
[5.29 2.23 0.01 0.09 0.24 0.33 0.68 0.53 0.04 0.57]




KeyboardInterrupt: 

In [12]:
pd.DataFrame(yhat[i][0])

0             1             2             3             4  \
0    2.101391e-08  4.132796e-09  2.190325e-11  1.694792e-10  3.543194e-10   
1    6.247894e-01  4.716526e-05  3.153489e-07  2.698017e-05  3.246356e-01   
2    1.452952e-07  9.999998e-01  7.607038e-14  1.369651e-11  3.107785e-09   
3    8.626754e-01  7.168840e-02  3.308425e-07  9.207132e-05  2.198758e-02   
4    7.444239e-01  6.913825e-02  8.113943e-05  5.198091e-04  1.546540e-02   
..            ...           ...           ...           ...           ...   
115  1.000000e+00  2.123007e-09  4.968377e-13  5.404895e-12  8.809721e-11   
116  1.000000e+00  2.897780e-09  5.295815e-13  6.001291e-12  1.055617e-10   
117  1.000000e+00  4.465414e-09  4.945930e-13  7.347243e-12  1.423710e-10   
118  1.000000e+00  5.061068e-09  9.978047e-13  1.591738e-11  1.065724e-10   
119  1.000000e+00  5.407956e-09  7.444663e-12  5.694420e-11  1.786697e-10   

                5             6             7             8             9  
0    2.276853e-11  1.000000e+00  1.580019e-09  7.502141e-11  2.187117e-09  
1    5.591124e-05  4.516846e-02  1.504639e-04  3.256642e-04  4.799996e-03  
2    1.204313e-11  4.141917e-09  1.064783e-07  4.378411e-08  6.005017e-10  
3    1.001615e-04  6.756294e-03  2.259525e-02  9.323493e-05  1.401136e-02  
4    6.755184e-04  6.173403e-02  4.816861e-02  3.437820e-03  5.635551e-02  
..            ...           ...           ...           ...           ...  
115  4.327113e-12  4.122478e-11  8.061743e-11  4.114505e-11  6.439275e-10  
116  4.600191e-12  5.396904e-11  8.054535e-11  4.497609e-11  6.968163e-10  
117  5.265481e-12  8.807352e-11  8.482979e-11  5.310477e-11  6.275059e-10  
118  5.199096e-12  1.438049e-10  2.727538e-10  7.768504e-11  6.750736e-10  
119  2.607240e-11  9.010716e-10  1.360926e-09  2.313318e-10  1.117277e-09  

[120 rows x 10 columns]

In [39]:
# how to assemble this in to a figure that can be used to help assess the quality

# might need to be a different way to train the model - the model seems to learn what an unknown looks like

[4, 4, 6, 6, 6, 6, 7, 6, 6, 6]
[0.01 0.05 0.   0.01 2.36 0.22 6.32 0.57 0.32 0.13]


[4, 0, 1, 1, 0, 0, 0, 1, 0, 0]
[3.94 3.09 0.   0.01 1.91 0.21 0.42 0.16 0.07 0.19]


[0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
[5.67 2.78 0.   0.09 0.34 0.07 0.19 0.07 0.04 0.75]


[0, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[5.38 2.24 0.   0.02 1.43 0.03 0.39 0.33 0.07 0.11]


[4, 0, 4, 0, 0, 0, 0, 9, 0, 0]
[5.56 0.66 0.   0.05 1.95 0.04 0.37 0.64 0.08 0.64]


[0, 0, 0, 0, 0, 1, 0, 0, 0, 1]
[5.29 2.23 0.01 0.09 0.24 0.33 0.68 0.53 0.04 0.57]


[4, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[7.57 0.05 0.   0.16 1.67 0.02 0.36 0.05 0.02 0.11]


[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
[4.28 3.71 0.   0.44 0.63 0.06 0.42 0.35 0.03 0.07]


[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[1.63 8.16 0.   0.01 0.07 0.   0.08 0.02 0.02 0.01]


[0, 0, 0, 0, 0, 9, 6, 0, 0, 6]
[6.14 0.96 0.   0.11 0.41 0.08 1.41 0.03 0.08 0.77]


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[7.08 0.51 0.   0.11 0.44 0.07 0.39 0.57 0.08 0.74]


[4, 9, 0, 0, 0, 1, 0, 0, 0, 0]
[5.26 0.69 0.   0.01 1.7  0.32 0.3

KeyboardInterrupt: 

In [ ]:
# in this way predict the function of a known gene

#is it that my unknown masking is different from the known masking and the model is getting confused

In [42]:
np.array(scores).sum(axis=0)

[1, 1, 4, 1, 4, 1, 7, 1, 1, 7]
[0.01 4.78 0.   0.03 1.51 0.   1.38 1.99 0.09 0.21]


[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]


[8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
[ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]


[8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
[ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]


[8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
[0.   0.   0.08 0.   0.   0.   0.   0.   9.91 0.  ]


[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]


[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]


[6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
[0.   0.   0.   0.   0.01 0.   9.73 0.27 0.   0.  ]


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
[0.   0.08 0.   0.   0.01 0.   0.01 9.9  0.   0.01]


[8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
[0.   0.   0.   0.02 0.   0.   0.   0.   9.98 0.  ]


[4, 7, 4, 7, 7, 5, 4, 7, 7, 6]
[0.01 0.48 0.   0.03 3.28 0.75 1.45 3.48 0.04 0.48]


[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]


[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
[ 0.  0. 

In [36]:
# problem is also my weird approach I used where I ignored the softmax unknown class

53


In [37]:
x[i]

7.794117647058823

In [56]:
# drop off the x values which are emtpy in a column #column 14

# get the rows which don't have a value in gene length
np.where(x[i][:, 14] == 0)[0][0]

37

In [59]:
#identify the unknowns
[j for j in list(np.where(x[i][:, 0] == 1)[0]) if j < np.where(x[i][:, 14] == 0)[0][0]]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 19, 21, 25, 31, 36]

In [70]:
x[0][u][:10] = np.zeros(10)

In [161]:
x[0]
statistics.get_masked(x[11], 10)
#x[0][12] #this does not appear to be the masked

22

In [88]:
statistics.get_masked(x[1],10)

3

In [90]:
yhat = [m.predict(x[1].reshape(1,120,16)) for m in models]

1/1 [==============================] - 0s 27ms/step


In [94]:
[yhat[i][0][3] for i in range(len(yhat))]

[array([4.2393065e-08, 6.1843079e-11, 1.2827230e-10, 9.9999917e-01,
        7.8784120e-07, 6.5667383e-13, 1.5811744e-10, 3.6584963e-10,
        2.1661750e-09, 4.9444915e-10], dtype=float32),
 array([4.2985491e-08, 1.9203084e-08, 6.4222849e-09, 9.9999917e-01,
        3.5984225e-08, 9.6069774e-09, 1.7358724e-09, 1.7916670e-07,
        5.1104621e-07, 1.0914610e-09], dtype=float32),
 array([3.1004685e-08, 1.3435717e-08, 5.5513773e-08, 9.9999797e-01,
        1.1604248e-08, 1.5273036e-11, 8.9232322e-10, 1.4842902e-07,
        1.7917785e-06, 8.9862014e-11], dtype=float32),
 array([3.9515456e-08, 6.2562052e-08, 3.9243705e-08, 9.9999964e-01,
        1.5044304e-08, 4.6021426e-10, 6.9930312e-10, 1.8249103e-09,
        5.7956523e-08, 3.2531924e-09], dtype=float32),
 array([2.1797835e-06, 3.2117759e-07, 6.8005654e-08, 9.9998701e-01,
        3.1352169e-08, 3.0201938e-10, 5.9551679e-09, 2.1215581e-06,
        8.1851213e-06, 2.5340221e-08], dtype=float32),
 array([1.2162706e-08, 2.4487460e-07, 1.30027

In [164]:
y[11][22]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [165]:
yhat = [m.predict(x[11].reshape(1,120,16)) for m in models]

1/1 [==============================] - 0s 28ms/step


In [168]:
[yhat[i][0][22][3] for i in range(10)]

[0.9998004,
 0.99988663,
 0.99976116,
 0.99961394,
 0.99984324,
 0.9977805,
 0.99982834,
 0.99999297,
 0.9998628,
 0.99997973]

In [278]:
#this looks accurate - so what is the problem
x[89]

array([[  0.,   0.,   0., ...,   0., 537.,   0.],
       [  0.,   0.,   0., ..., 518., 303.,   1.],
       [  0.,   0.,   0., ..., -23., 540.,   2.],
       ...,
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.]])

In [279]:
# try with an unknown to evaluate if the same contegroy is consistently predicted
a = x[89]
a[6][:10]  = np.zeros(10)# replacing with a zero

In [280]:
a

array([[  0.,   0.,   0., ...,   0., 537.,   0.],
       [  0.,   0.,   0., ..., 518., 303.,   1.],
       [  0.,   0.,   0., ..., -23., 540.,   2.],
       ...,
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.]])

In [281]:
yhat = [m.predict(a.reshape(1, 120, 16)) for m in models]

1/1 [==============================] - 0s 27ms/step


In [282]:
[yhat[i][0][6] for i in range(10)]

[array([9.0187943e-01, 3.1584859e-06, 5.8178187e-09, 9.8092616e-02,
        4.2591459e-08, 4.2732069e-08, 1.8130973e-07, 9.5364008e-08,
        2.4442772e-05, 2.8174911e-09], dtype=float32),
 array([9.8977566e-01, 3.6240892e-06, 3.1932707e-06, 1.0181206e-02,
        5.1805036e-09, 7.6153228e-08, 2.0067846e-06, 3.2547669e-05,
        1.6700606e-06, 1.0937925e-11], dtype=float32),
 array([9.7059286e-01, 3.6863545e-07, 1.7765035e-07, 2.9392008e-02,
        2.7754654e-06, 4.5772608e-06, 4.6591649e-06, 3.0599830e-07,
        2.1829278e-06, 1.8098565e-09], dtype=float32),
 array([7.2538155e-01, 9.6017866e-06, 1.3445081e-07, 2.7450734e-01,
        8.3015868e-07, 9.6670952e-08, 3.7562555e-07, 9.5754200e-05,
        4.2809488e-06, 1.1253107e-09], dtype=float32),
 array([9.1670251e-01, 8.3272300e-07, 9.0892680e-09, 8.3286293e-02,
        1.4313896e-07, 3.2623029e-07, 1.2195295e-06, 1.4995749e-06,
        7.1959626e-06, 1.1349883e-11], dtype=float32),
 array([9.5621496e-01, 6.6058878e-05, 5.18981

In [283]:
[np.argmax(yhat[i][0][6]) for i in range(10)] #for this unknown some replicates say it is 8 and others are unknown

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [285]:
np.array(yhat)[:,0,6].sum(axis=0) #this demonstrates that using the phynteny score is useful

array([9.3085737e+00, 1.0660822e-04, 5.5697910e-06, 6.8984610e-01,
       1.5053815e-05, 3.8739217e-05, 4.2988180e-05, 1.3971925e-04,
       1.2309559e-03, 1.8574495e-07], dtype=float32)

In [ ]:
# can see here that the score increases for the unknown
# hopefully helps to create a more accurate scoring

In [ ]:
# can see that it indeed does work for predicting unknowns

In [326]:
from phynteny_utils import predictor
from phynteny_utils import format_data
from importlib import reload
reload(predictor)

<module 'phynteny_utils.predictor' from '/Users/susiegrigson/PycharmProjects/Phynteny/phynteny_utils/predictor.py'>

In [357]:
test_phage = pickle5.load(open('test_data/phynteny_data_test_prophages.pkl', 'rb'))

In [359]:
test_phage.keys()

dict_keys([44186, 571720, 543185, 92668, 828409, 637611, 427634, 637265, 810624, 138016, 737039, 21174, 36688, 37815, 545855, 981370, 796667, 595828, 680726, 377156, 854220, 315567, 945919, 233137, 244044, 748184, 597422, 337016, 199674, 462819, 472703, 892436, 410976, 622699, 599251, 721388, 669014, 816671, 225472, 713294, 134694, 16640, 834921, 811427, 922452, 709779, 578750, 19487, 788087, 570067, 246409, 730402, 934094, 445116, 98088, 322672, 443281, 366856, 41285, 148512, 476747, 419709, 737796, 554636, 905927, 500272, 191529, 381030, 215616, 755952, 576362, 569587, 669959, 734725, 926719, 183425, 274881, 824300, 184082, 957936, 706866, 619991, 959204, 30371, 400557, 115421, 120111, 654754, 358804, 431636, 430759, 671956, 455382, 549345, 551645, 193693, 734506, 213045, 548504, 188434, 754610, 731148, 687430, 373957, 711967, 685981, 11121, 487858, 579008, 793132, 878678, 624598, 644029, 349141, 935288, 169715, 227844, 911775, 115989, 571180, 373965, 371151, 658130, 174887, 249050, 

In [309]:
X, y= format_data.generate_dataset(test_phage,'all', 10, 120 )

In [342]:
X[1]
p = predictor.Predictor('test_data/test_model/grid_search_model.m_200.b_256.lr_0.0001.dr_0.1.l_2.a_tanh.o_adam.rep_0.best_val_loss.h5', 'phynteny_utils/phrog_annotation_info/phrog_integer.pkl',
                                'phynteny_utils/phrog_annotation_info/phrog_integer.pkl', 'phynteny_utils/phrog_annotation_info/integer_category.pkl')

In [353]:
type(list(pickle5.load(open('phynteny_utils/phrog_annotation_info/phrog_integer.pkl', 'rb')).keys())[0])

int

In [348]:
test_phage.get('GCA_019958435_ABCLCC010000060.1_PP6').get('phrogs')

['105',
 '295',
 '2243',
 '31',
 '28576',
 '28576',
 '18',
 '14',
 '24',
 '32165',
 '42',
 '215',
 '37',
 '27',
 '153',
 '122',
 '133',
 '21',
 '118',
 '15',
 '141',
 '31861',
 '312',
 '181',
 '217',
 '198',
 'No_PHROG']