In [61]:
# imports
from phynteny_utils import train_model
import pickle
from phynteny_utils import format_data
import numpy as np
from phynteny_utils import statistics
import tensorflow as tf

In [57]:
# read in some data
X = pickle.load(open('test_data/x_mini.pkl', 'rb'))
y = pickle.load(open('test_data/y_mini.pkl', 'rb'))

for key in list(X.keys()):

    m = X.get(key)
    #idx = statistics.get_masked(m, 10)
    #m[idx][0:10] = np.ones(10)*-1

    idx = np.where(m[:,0] == 1)
    for i in idx[0]:
        m[i][0:10] = np.ones(10)*-1

    X[key] = m

pickle.dump(X, open('test_data/x_mini_masked.pkl', 'wb'))

In [16]:
X_masked = pickle.load(open('test_data/x_mini_masked.pkl', 'rb'))
statistics.get_masked(X_masked.get(key),10)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [17]:
a = X_masked.get(key)
np.where(a==-1)

(array([14, 28, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35]),
 array([13, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9]))

In [59]:
m = train_model.Model()
m.parse_masked_data('test_data/x_mini_masked.pkl', 'test_data/y_mini.pkl')

In [60]:
m.train_crossValidation()

/Users/susiegrigson/opt/anaconda3/envs/phynteny/lib/python3.8/site-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_5 (Masking)         (None, 120, 16)           0         
                                                                 
 bidirectional_10 (Bidirecti  (None, 120, 200)         93600     
 onal)                                                           
                                                                 
 bidirectional_11 (Bidirecti  (None, 120, 200)         240800    
 onal)                                                           
                                                                 
 time_distributed_5 (TimeDis  (None, 120, 10)          2010      
 tributed)                                                       
                                                                 
Total params: 336,410
Trainable params: 336,410
Non-trainable params: 0
________________________________________________

INFO:tensorflow:Assets written to: model.rep_0.final_model/assets


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_6 (Masking)         (None, 120, 16)           0         
                                                                 
 bidirectional_12 (Bidirecti  (None, 120, 200)         93600     
 onal)                                                           
                                                                 
 bidirectional_13 (Bidirecti  (None, 120, 200)         240800    
 onal)                                                           
                                                                 
 time_distributed_6 (TimeDis  (None, 120, 10)          2010      
 tributed)                                                       
                                                                 
Total params: 336,410
Trainable params: 336,410
Non-trainable params: 0
________________________________________________

INFO:tensorflow:Assets written to: model.rep_1.final_model/assets


Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_7 (Masking)         (None, 120, 16)           0         
                                                                 
 bidirectional_14 (Bidirecti  (None, 120, 200)         93600     
 onal)                                                           
                                                                 
 bidirectional_15 (Bidirecti  (None, 120, 200)         240800    
 onal)                                                           
                                                                 
 time_distributed_7 (TimeDis  (None, 120, 10)          2010      
 tributed)                                                       
                                                                 
Total params: 336,410
Trainable params: 336,410
Non-trainable params: 0
________________________________________________

KeyboardInterrupt: 

In [62]:
model = tf.keras.models.load_model('model.rep_0.best_val_loss.h5')

In [69]:
a = model.predict(X[key].reshape(1,120,16))

1/1 [==============================] - 0s 26ms/step


In [73]:
pd.DataFrame(a[0])

0         1         2         3         4         5         6  \
0    0.103874  0.100708  0.099481  0.099897  0.099149  0.099727  0.099246   
1    0.104389  0.100753  0.099320  0.099821  0.099083  0.099659  0.099196   
2    0.104804  0.100778  0.099185  0.099760  0.099034  0.099601  0.099176   
3    0.105137  0.100790  0.099071  0.099713  0.098997  0.099551  0.099175   
4    0.105407  0.100795  0.098977  0.099678  0.098969  0.099508  0.099186   
..        ...       ...       ...       ...       ...       ...       ...   
115  0.105469  0.100358  0.098760  0.099616  0.099147  0.099320  0.099509   
116  0.105245  0.100299  0.098782  0.099609  0.099205  0.099334  0.099559   
117  0.104973  0.100237  0.098803  0.099601  0.099272  0.099349  0.099627   
118  0.104644  0.100173  0.098822  0.099589  0.099353  0.099362  0.099716   
119  0.104246  0.100112  0.098834  0.099573  0.099448  0.099373  0.099835   

            7         8         9  
0    0.099062  0.099682  0.099174  
1    0.099009  0.099659  0.099113  
2    0.098955  0.099636  0.099072  
3    0.098904  0.099615  0.099045  
4    0.098856  0.099596  0.099028  
..        ...       ...       ...  
115  0.098996  0.099551  0.099275  
116  0.099065  0.099572  0.099329  
117  0.099143  0.099601  0.099394  
118  0.099227  0.099641  0.099472  
119  0.099317  0.099695  0.099566  

[120 rows x 10 columns]

In [74]:
y[key]

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])